// 中文（简体）版演示数据 — 与 lib/demoCareData.ts 结构一致。
// 品牌与计划名称保留英文：AiMao、CareKaki、Guardian、CHAS、MediFund、SingPass、ICCP、HDB EASE、AIC、SACH。
// 演示用合成数据 — 不含真实病人信息。

import type { CareDataBundle } from "./careData";

export const zhCareData: CareDataBundle = {
  todayPlan: [
    { time: "上午 9:00", title: "晨间散步", done: true },
    { time: "下午 3:00", title: "起坐练习" },
    { time: "下午 5:00", title: "补水提醒" },
  ],

  todaySummary: {
    headline: "今天情况大致稳定。",
    detail: "有一个小变化值得留意 — 这周的胃口比平时差一些。",
  },

  weeklySchedule: [
    { day: "周一", items: ["晨间散步", "起坐练习", "补水检查"] },
    { day: "周二", items: ["平衡练习", "高蛋白早餐", "慧玲来电"] },
    { day: "周三", items: ["晨间散步", "起坐练习", "药物检查"] },
    { day: "周四", items: ["社区中心活动", "补水检查"] },
    { day: "周五", items: ["晨间散步", "起坐练习", "体重记录"] },
    { day: "周六", items: ["家庭午餐", "温和伸展"] },
    { day: "周日", items: ["休息日", "备好一周药盒"] },
  ],

  activityCompletion: [
    { activity: "晨间散步", done: 22, planned: 26 },
    { activity: "起坐练习", done: 9, planned: 12 },
    { activity: "补水检查", done: 24, planned: 26 },
    { activity: "平衡练习", done: 5, planned: 8 },
    { activity: "社交活动", done: 3, planned: 4 },
  ],

  careDomains: [
    { domain: "行动能力", attention: 72, tone: "drawer-orange" },
    { domain: "营养", attention: 64, tone: "drawer-yellow" },
    { domain: "药物", attention: 35, tone: "drawer-blue" },
    { domain: "社交", attention: 28, tone: "drawer-green" },
  ],

  carePlanSummary: {
    paragraphs: [
      "本护理计划聚焦于保持下肢力量、支持规律饮食，并留意近期站立稳定性的变化。各项活动融入日常作息，家人无需专业设备即可协助完成。",
      "计划兼顾三类工作：保护体力与独立性的日常活动、可解锁经济与社区支持的补助申请，以及一个单一联络点 — 让家人不必独自协调一切。",
    ],
    priorities: ["通过短时、规律的练习保持下肢力量", "支持规律的饮食与补水", "留意近期站立稳定性的变化"],
    strengths: ["在家中能独立行走", "家人每天都会问候", "使用药盒，服药可靠"],
    monitor: ["站立稳定性（本周两次需要扶助）", "早餐胃口（近期三个早晨吃得少）"],
    weeklyGoals: ["完成 3 次起坐练习", "7 次补水检查至少完成 6 次", "参加一次户外社交活动"],
    caregiverInvolvement:
      "由一位家人协助平衡与起坐练习、参加每周回顾，并把任何异常告诉 AiMao — 20 秒的一句话就够了。",
  },

  activityDetails: {
    "home-safety": {
      purpose: "在造成伤害之前，清除家中最常见的跌倒隐患 — 松动的地垫、昏暗的走廊、拖地的电线。",
      duration: "30–45 分钟，一次",
      frequency: "现在一次，之后每 3 个月复查",
      difficulty: "容易",
      equipment: "无 — 手机手电筒即可",
      steps: [
        "沿平日路线走一遍：床 → 厕所 → 厨房 → 沙发 → 门口。",
        "移除或用胶带固定沿线松动的地毯和电线。",
        "检查每条走廊和厕所的灯是否够亮、正常工作。",
        "在卧室到厕所之间加一盏小夜灯。",
        "清理走道上的杂物、矮凳和低矮家具边角。",
        "记下需要加装扶手的位置（厕所、淋浴间、床边）。",
      ],
      caregiverRole: "一起走这一遍 — 住在这里的人最熟悉自己的路线；您能发现他们已经习以为常的隐患。",
      stopIf: [],
      why: "最近发生过跌倒，之后家里还没检查过。大多数再次跌倒都发生在与第一次相同的路线上。",
    },
    "walker-fit": {
      purpose: "合适的助行器和扶手，把不稳的时刻 — 起床、走出淋浴间 — 变成安全的时刻。",
      duration: "1 次调试（约 1 小时）",
      frequency: "一次，之后按需调整",
      difficulty: "容易",
      equipment: "助行器（租借或购买），扶手可通过 HDB EASE 或承包商安装",
      steps: [
        "穿平常的鞋站直；手臂自然下垂时，助行器把手应与手腕齐平。",
        "练习顺序：助行器先向前 → 较弱的腿 → 较强的腿。",
        "在马桶旁和淋浴间内安装扶手。",
        "练习用扶手坐下和站起，不要抓毛巾架。",
        "每月检查助行器的橡胶脚垫，磨损就更换。",
      ],
      caregiverRole: "最初几次练习时，稍微走在侧后方。让器材承重 — 除非对方开口，不要伸手搀扶。",
      stopIf: ["行走时出现新的疼痛", "助行器感觉不稳或摇晃"],
      why: "跌倒后曾报告走路不稳 — 合适的器材能恢复自信、独立的行动。",
    },
    "caregiver-basics": {
      purpose: "让家庭照顾者掌握实用技能 — 安全搬移、用药规律、观察要点 — 让照顾可以长久。",
      duration: "半天课程",
      frequency: "一次，每年复训",
      difficulty: "容易",
      equipment: "无 — 课程由 AIC 的护老者培训津贴支持",
      steps: [
        "申请护老者培训津贴（每年最高 $200）。",
        "报名住家附近的『长者照护基础』课程。",
        "学习安全搬移技巧：站稳、一起数数、慢慢移动。",
        "建立共享的用药和复诊日历。",
        "把夜间求助热线放在显眼的地方。",
      ],
      caregiverRole: "这一项是给您的 — 正在照顾家人的您。",
      stopIf: [],
      why: "女儿是主要照顾者，还没接受过正式培训。受过培训的照顾者更不易倦怠，也能更早发现问题。",
    },
    "home-nursing": {
      purpose: "社区护士上门处理伤口、量体征、核对药物 — 康复继续进行，不必疲于奔波诊所。",
      duration: "每次 45–60 分钟",
      frequency: "起初每周一次，随康复逐步减少",
      difficulty: "容易 — 由护士操作",
      equipment: "无",
      steps: [
        "AiMao 起草居家护理服务的转介。",
        "确认上门日期，把药物清单放在桌上。",
        "每次上门：检查体征、伤口和任何新症状。",
        "有问题尽管问护士 — 两次上门之间把问题写下来。",
        "护士的记录会汇入护理简报，供护理团队查看。",
      ],
      caregiverRole: "第一次上门尽量在场；之后护士和 AiMao 会随时向您通报。",
      stopIf: [],
      why: "出院后的康复需要专业人员定期查看，而目前去诊所复诊比较困难。",
    },
    "physio-sach": {
      purpose: "系统的物理治疗能重建跌倒后失去的力量和平衡 — 这是预防再次跌倒最有效的方法。",
      duration: "每节 45 分钟",
      frequency: "每周 2 节，共 6–8 周",
      difficulty: "中等 — 有挑战但安全",
      equipment: "舒适的鞋子；其余由社区医院提供",
      steps: [
        "先到 SACH 社区医院做初步评估。",
        "按处方进行训练 — 通常是腿部力量、平衡训练和步行练习。",
        "非训练日在家做简化版的家庭练习。",
        "任何头晕或疼痛立刻告诉物理治疗师。",
        "第 4 周复评并调整训练强度。",
      ],
      caregiverRole: "训练日帮忙接送，并鼓励完成家庭练习 — 坚持比强度更重要。",
      stopIf: ["运动中胸口不适", "休息后仍不缓解的头晕", "关节剧痛"],
      why: "跌倒后行动能力还没完全恢复。有督导的康复训练是重新独立行走的循证之路。",
    },
    "med-review": {
      purpose: "由药剂师把所有药物 — 出院新药加原有药物 — 一起检查，排查相互作用、重复用药和增加跌倒风险的副作用。",
      duration: "30 分钟",
      frequency: "现在一次，之后每次住院后复查",
      difficulty: "容易",
      equipment: "带上所有药盒，包括保健品",
      steps: [
        "把现有的每种药、保健品和中药装进一个袋子。",
        "在常去的综合诊疗所或药房预约药物复查。",
        "特别问一句：『这些药里有没有会增加跌倒风险的？』",
        "按检查结果更新药盒和药物清单。",
        "把更新后的清单告诉 AiMao，让护理简报保持最新。",
      ],
      caregiverRole: "帮忙收集药物并陪同复查 — 用药指示有变时，多一双耳朵总是好的。",
      stopIf: [],
      why: "出院时新增了药物。多种常见药物合用会增加嗜睡和跌倒风险。",
    },
    hcg: {
      purpose: "居家看护津贴（Home Caregiving Grant）为有永久性中度失能者的家庭提供每月 $250–$400 的看护开支补助。",
      duration: "申请约 30 分钟",
      frequency: "一次 — AIC 定期复核",
      difficulty: "容易",
      equipment: "SingPass、家庭收入资料",
      steps: [
        "确认资格：日常活动中有 3 项或以上需要协助。",
        "可能需要功能评估报告 — 综合诊疗所可以安排。",
        "用 SingPass 在 AIC 网站上申请。",
        "提交家庭收入资料以进行经济审查。",
        "批准后津贴按月发放。",
      ],
      caregiverRole: "申请通常由家庭照顾者完成。",
      stopIf: [],
      why: "家庭人均收入在符合资格的范围内 — 这是政府为这种处境的家庭准备的钱。",
    },
    medifund: {
      purpose: "MediFund 是一张安全网：当补贴、MediShield 和 MediSave 都不够时，帮助支付剩余的医疗费。",
      duration: "到医院/诊所收费处询问即可",
      frequency: "按账单、按需申请",
      difficulty: "容易 — 有医务社工协助",
      equipment: "近期账单、收入证明",
      steps: [
        "向就诊医院的医务社工询问 MediFund。",
        "带上近期账单和家庭收入证明。",
        "由社工代为提交申请。",
        "批准的金额直接抵扣账单。",
      ],
      caregiverRole: "陪同赴医务社工的面谈。",
      stopIf: [],
      why: "康复会在几个月里持续产生费用 — 这能避免康复变成经济负担。",
    },
    chas: {
      purpose: "CHAS 卡让邻里诊所的普通科和牙科就诊享有补贴 — 常规复诊在家附近就能负担得起。",
      duration: "线上 10 分钟",
      frequency: "一次 — 自动续期",
      difficulty: "容易",
      equipment: "SingPass",
      steps: [
        "用 SingPass 到 chas.sg 申请或查询等级。",
        "获批后，选一家住家附近的 CHAS 诊所做复诊。",
        "每次就诊出示卡片，即可享受补贴价。",
      ],
      caregiverRole: "如有需要，协助完成线上申请。",
      stopIf: [],
      why: "目前门诊复诊频繁 — 有了这张卡，同样的就诊费用会低很多。",
    },
    iccp: {
      purpose: "一位指定的护理协调员把一切串起来 — 预约、服务、申请 — 家人再也不用追着五个机构跑。",
      duration: "长期关系",
      frequency: "每月跟进，有变化时更频繁",
      difficulty: "容易",
      equipment: "无",
      steps: [
        "AiMao 准备好护理简报，把个案移交给 ICCP 协调员。",
        "协调员与家人确认计划。",
        "此后只需记一个电话号码 — 其余由协调员去追。",
        "每月跟进，随需要更新计划。",
      ],
      caregiverRole: "存好协调员的号码，有任何不对劲就提出来 — 没有太小的问题。",
      stopIf: [],
      why: "护理涉及很多环节。有单一联络点，才是真正的计划，而不是一叠传单。",
    },
    "family-loop": {
      purpose: "一个简单的每月节奏，让每位家人都知情，也一起分担照顾。",
      duration: "每月 20 分钟",
      frequency: "每月一次，有变化时随时更新",
      difficulty: "容易",
      equipment: "家庭群聊",
      steps: [
        "定一个每月固定的家庭碰头 — 通话或一起吃饭都行。",
        "一起看护理简报：有什么变化、接下来做什么。",
        "轮流陪同物理治疗或护士上门。",
        "商定 AiMao 发出提醒时由谁先响应。",
      ],
      caregiverRole: "由您来主持 — 但重点是：这个计划不再由您一个人扛。",
      stopIf: [],
      why: "家人都在也愿意帮忙 — 一点轻结构就能把善意变成实实在在的分担。",
    },
    "alert-device": {
      purpose: "可穿戴的紧急按钮，跌倒后立即联系家人或 24 小时响应中心 — 独居时至关重要。",
      duration: "设置约 1 小时",
      frequency: "每天佩戴",
      difficulty: "容易",
      equipment: "个人紧急按钮（挂坠式或腕带式）",
      steps: [
        "选一款真的会戴的设备 — 挂坠或腕带都行。",
        "按顺序设置紧急联系人：先家人，再响应中心。",
        "每月一起测试一次。",
        "洗澡时也要戴 — 家里大多数跌倒发生在浴室。",
      ],
      caregiverRole: "每月一起做测试呼叫，让按下按钮永远不是一件可怕的事。",
      stopIf: [],
      why: "跌倒后独居，意味着求助必须是一按即达，而不是一通电话之外。",
    },
    "silver-support": {
      purpose: "立国一代补助（Silver Support）每季度向一生收入较低的长者发放现金补贴 — 符合条件无需申请。",
      duration: "自动",
      frequency: "每季度发放",
      difficulty: "容易",
      equipment: "无",
      steps: [
        "资格由 CPF 和住房记录自动评估。",
        "用 SingPass 在 Silver Support 网站查询状态。",
        "补贴每季度存入登记的银行账户。",
      ],
      caregiverRole: "只需确认补贴有按时到账。",
      stopIf: [],
      why: "MyInfo 显示的退休金等级表明可能符合资格 — 这可能是本来就该拿到的钱。",
    },
    aac: {
      purpose: "附近的活跃乐龄中心每天有活动、运动小组和友伴计划 — 离家几分钟就有陪伴和寄托。",
      duration: "工作日随时可去",
      frequency: "先从每周 2 次开始",
      difficulty: "容易",
      equipment: "无",
      steps: [
        "先去最近的活跃乐龄中心看一次 — 参观不用报名。",
        "选一个喜欢的固定活动（运动、手工、喝咖啡聊天）。",
        "询问友伴计划，安排每周探访。",
      ],
      caregiverRole: "第一次一起去能降低门槛；之后它就会变成习惯。",
      stopIf: [],
      why: "独居、家人在海外 — 孤独是健康风险，而这里就是它的解药。",
    },
    "med-flag": {
      purpose: "将当前药物清单标记为需要临床医生主导的复查 — AiMao 自己不评估心脏药物。",
      duration: "由诊所处理",
      frequency: "紧急 — 本周内",
      difficulty: "容易",
      equipment: "当前药物清单",
      steps: [
        "AiMao 把药物清单和近期情况发给诊所，标记为需要复查。",
        "诊所安排由临床医生主导的药物复查。",
        "在此之前：未经医生同意，不改动任何药物。",
      ],
      caregiverRole: "确保这个预约在本周内完成。",
      stopIf: [],
      why: "昏厥后使用多种心脏药物，严格属于临床医生的领域。安全的做法是快速移交，而不是 AI 的意见。",
    },
    "falls-review": {
      purpose: "系统的跌倒与行动能力评估，找出反复不稳背后的原因 — 鞋子、视力、血压或肌力。",
      duration: "1 次门诊",
      frequency: "一次，之后遵医嘱",
      difficulty: "容易",
      equipment: "带上现用的拐杖和平常穿的鞋",
      steps: [
        "预约跌倒门诊评估（转介由协调员安排）。",
        "评估内容包括平衡、步态、站立血压、视力和鞋子。",
        "遵循评估后的方案 — 往往是小改动、大效果。",
      ],
      caregiverRole: "陪同评估，帮忙回忆跌倒经过。",
      stopIf: [],
      why: "有跌倒史，拄杖仍不稳，需要找出原因，而不是只处理症状。",
    },
    escalate: {
      purpose: "近期昏厥，加上心衰和抗凝药物，需要立刻有临床医生和协调员接手。",
      duration: "本周内",
      frequency: "紧急，一次",
      difficulty: "由专业人员处理",
      equipment: "无",
      steps: [
        "AiMao 把情况整理成护理简报，升级给协调员。",
        "协调员确认几天内（而不是几周内）安排临床复诊。",
        "结果和下一步会及时告知家人。",
      ],
      caregiverRole: "每一步都会通知侄子。",
      stopIf: [],
      why: "这种情况超出了任何应用该处理的范围。负责任的做法是快速、完整地移交给人。",
    },
    "nephew-loop": {
      purpose: "让唯一在场的家人 — 每周来访的侄子 — 随时知情，又不增加他的负担。",
      duration: "每周几分钟",
      frequency: "每周摘要 + 紧急提醒",
      difficulty: "容易",
      equipment: "手机",
      steps: [
        "侄子每周收到护理简报摘要。",
        "紧急提醒第一时间发给他，可一键回应。",
        "他探访时的观察直接反馈给 AiMao。",
      ],
      caregiverRole: "这是侄子的专属通道 — 特意设计得很轻。",
      stopIf: [],
      why: "没有主要照顾者时，每周来访的人就是安全网 — 他需要的是信号，不是噪音。",
    },
  },

  fallbackDetail: {
    purpose: "当前护理计划的一部分 — 可以让 AiMao 完整解释这一步。",
    duration: "视情况",
    frequency: "按计划",
    difficulty: "容易",
    equipment: "无",
    steps: ["让 AiMao 一步一步带您完成这项活动。"],
    caregiverRole: "问问 AiMao 怎样协助这一项最好。",
    stopIf: [],
    why: "根据您与 AiMao 的对话加入计划。",
  },

  briefRecentChanges: ["近期三个早晨早餐吃得少", "活动量连续 4 天低于个人基线", "本周两次站立时需要扶助"],

  briefTimeline: [
    { day: "周一", note: "晚餐吃得少" },
    { day: "周二", note: "活动量低于平常范围" },
    { day: "周三", note: "早餐吃得少" },
    { day: "周四", note: "站立时需要扶助" },
  ],

  briefWhyFlagged: ["胃口变化连续几天重复出现", "同一时间窗内出现了新的行动能力变化", "该模式偏离了个人基线"],

  briefDiscussPoints: ["站立困难从什么时候开始", "有没有疼痛或头晕", "近期的胃口和饮水", "近期有没有药物调整"],
};
